# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cr2-8qI6jspvXYdTkBZGOG1jDixZzsw-
"""

import zipfile
import os

# Path to your uploaded zip file (update the filename if different)
zip_path = "/content/Label Annotations.v4i.yolov8.zip"
extract_path = "/content/"

# Unzip
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ Dataset extracted to:", extract_path)
print("Contents:", os.listdir(extract_path))

import os
import random
import shutil

# Paths
dataset_path = "/content/train"
images_path = os.path.join(dataset_path, "images")
labels_path = os.path.join(dataset_path, "labels")

# Create train/val folders
for split in ["train", "val"]:
    os.makedirs(os.path.join(dataset_path, "images", split), exist_ok=True)
    os.makedirs(os.path.join(dataset_path, "labels", split), exist_ok=True)

# Get all image files
image_files = [f for f in os.listdir(images_path) if f.endswith(".jpg")]

# Shuffle and split (80% train, 20% val)
random.shuffle(image_files)
split_index = int(0.8 * len(image_files))
train_files = image_files[:split_index]
val_files = image_files[split_index:]

def move_files(files, split):
    for f in files:
        # Copy image
        shutil.copy(os.path.join(images_path, f), os.path.join(dataset_path, "images", split, f))
        # Copy label
        label_file = f.rsplit(".", 1)[0] + ".txt"
        shutil.copy(os.path.join(labels_path, label_file), os.path.join(dataset_path, "labels", split, label_file))

move_files(train_files, "train")
move_files(val_files, "val")

print("✅ Dataset split completed!")

from ultralytics import YOLO

# Load your previously trained model
model = YOLO("/content/best.pt")

# Retrain/fine-tune on new dataset
model.train(
    data="/content/data.yaml",
    epochs=30,          # you can adjust
    imgsz=640,
    batch=16,
    name="coupon_detector_finetuned",  # new training name
    lr0=0.001,          # optional: lower learning rate for fine-tuning
    pretrained=True     # ensures starting from best.pt weights
)

